#ifndef FRAME_SETTINGS
#define FRAME_SETTINGS

#define SAMPLING_RATE 48000
#define LOWER_FREQ 80
#define UPPER_FREQ 1000
#define LOWER_TAU (SAMPLING_RATE / UPPER_FREQ)
#define UPPER_TAU (SAMPLING_RATE / LOWER_FREQ)

#define WINDOW_SIZE (2 * UPPER_TAU)
#define BUFFER_SIZE (WINDOW_SIZE + UPPER_TAU)

#endif